import { CraftingRecipe, ItemDefinition, ItemType, SkillNode } from '../types';

export const NES_COLORS = {
  black: '#000000',
  darkGray: '#202020',
  midGray: '#585858',
  lightGray: '#A4A4A4',
  white: '#FFFFFF',
  
  nightDarkness: '#05070c',
  darkNavy: '#0c1024',
  deepBlue: '#152044',
  waterBlue: '#2038ec',
  skyCyan: '#3cbcfc',
  iceCyan: '#a4e4fc',

  deepGreen: '#004400',
  forestGreen: '#006800',
  grassGreen: '#00a800',
  limeGreen: '#58d854',
  foliageGreen: '#88f870',

  dirtBrown: '#503000',
  woodBrown: '#885818',
  logBrown: '#a87830',
  tanSand: '#e4a444',
  paleYellow: '#f8d878',

  bloodRed: '#881400',
  torchRed: '#d82800',
  fireOrange: '#fc7400',
  goldYellow: '#f8b800',
  pureYellow: '#fce000',

  purpleShadow: '#440068',
  cultistPurple: '#6820a0',
  mysticViolet: '#9858f8',
  poisonPink: '#f878f8',
  boneWhite: '#f8f8f8',
};

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = {
  wood: {
    id: 'wood',
    name: 'Madera de Pino',
    category: 'resource',
    description: 'Troncos recolectados de los pinos. Combustible vital para la fogata y crafteo.',
    iconPixel: '🪵',
    color: '#885818',
    maxStack: 99,
    fuelValue: 20,
  },
  stone: {
    id: 'stone',
    name: 'Piedra del Bosque',
    category: 'resource',
    description: 'Rocas resistentes para herramientas, fogata y trampas.',
    iconPixel: '🪨',
    color: '#888888',
    maxStack: 99,
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Mineral de Hierro',
    category: 'resource',
    description: 'Hierro crudo extraído de vetas rocosas misteriosas.',
    iconPixel: '⛏️',
    color: '#b0a090',
    maxStack: 50,
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Lingote Forjado',
    category: 'resource',
    description: 'Hierro refinado en la fogata para forjar armas de élite.',
    iconPixel: '🧱',
    color: '#d0d8e8',
    maxStack: 50,
  },
  berries: {
    id: 'berries',
    name: 'Bayas Silvestres',
    category: 'food',
    description: 'Frutos dulces del bosque. Calman el hambre ligera.',
    iconPixel: '🫐',
    color: '#d82860',
    maxStack: 30,
    hungerRestore: 15,
    healHp: 5,
  },
  raw_meat: {
    id: 'raw_meat',
    name: 'Carne Cruda',
    category: 'food',
    description: 'Carne fresca cazada. Cocínala en la fogata para evitar enfermedades.',
    iconPixel: '🥩',
    color: '#c03030',
    maxStack: 20,
    hungerRestore: 10,
    healHp: -5,
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Bife Asado',
    category: 'food',
    description: 'Carne asada al fuego crepitante. Gran aporte de salud y energía.',
    iconPixel: '🍖',
    color: '#904018',
    maxStack: 20,
    hungerRestore: 45,
    healHp: 30,
    warmthRestore: 15,
  },
  mushroom: {
    id: 'mushroom',
    name: 'Hongo Sombrío',
    category: 'food',
    description: 'Hongo que brota en rincones oscuros.',
    iconPixel: '🍄',
    color: '#a04870',
    maxStack: 30,
    hungerRestore: 10,
    fuelValue: 5,
  },
  mushroom_soup: {
    id: 'mushroom_soup',
    name: 'Sopa Caliente',
    category: 'food',
    description: 'Sopa reconstituyente. Regenera calor, salud y sacia el hambre.',
    iconPixel: '🍲',
    color: '#e4a444',
    maxStack: 10,
    hungerRestore: 60,
    healHp: 40,
    warmthRestore: 50,
  },
  wooden_club: {
    id: 'wooden_club',
    name: 'Garrote de Madera',
    category: 'weapon',
    description: 'Arma rudimentaria para defenderte de las alimañas.',
    iconPixel: '🏏',
    color: '#a87830',
    maxStack: 1,
    damage: 18,
    range: 36,
    attackSpeed: 450,
  },
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Hacha de Leñador',
    category: 'tool',
    description: 'Corta árboles con rapidez y hace buen daño a monstruos.',
    iconPixel: '🪓',
    color: '#885818',
    maxStack: 1,
    damage: 24,
    range: 40,
    attackSpeed: 400,
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Hacha de Hierro',
    category: 'tool',
    description: 'Tala pinos en segundos y aplasta sombras con contundencia.',
    iconPixel: '🪓',
    color: '#d0d8e8',
    maxStack: 1,
    damage: 42,
    range: 44,
    attackSpeed: 350,
  },
  hunting_spear: {
    id: 'hunting_spear',
    name: 'Lanza de Caza',
    category: 'weapon',
    description: 'Gran alcance de estocada. Mantiene a las bestias a raya.',
    iconPixel: '🗡️',
    color: '#c49a6c',
    maxStack: 1,
    damage: 35,
    range: 65,
    attackSpeed: 380,
  },
  machete: {
    id: 'machete',
    name: 'Machete de Explorador',
    category: 'weapon',
    description: 'Filo letal y corte veloz. Corta maleza y sombras por igual.',
    iconPixel: '🔪',
    color: '#e8e8e8',
    maxStack: 1,
    damage: 55,
    range: 48,
    attackSpeed: 280,
  },
  slingshot: {
    id: 'slingshot',
    name: 'Tirachinas Rápido',
    category: 'weapon',
    description: 'Dispara piedras a distancia para atraer o eliminar lobos.',
    iconPixel: '🏹',
    color: '#a87830',
    maxStack: 1,
    damage: 20,
    range: 220,
    attackSpeed: 350,
    ammoRequired: 'stone_ammo',
  },
  stone_ammo: {
    id: 'stone_ammo',
    name: 'Piedras de Proyectil',
    category: 'ammo',
    description: 'Piedras talladas para el tirachinas.',
    iconPixel: '⚪',
    color: '#a4a4a4',
    maxStack: 99,
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Arco de Caza Reforzado',
    category: 'weapon',
    description: 'Dispara flechas certeras con gran penetración y daño crítico.',
    iconPixel: '🏹',
    color: '#704010',
    maxStack: 1,
    damage: 60,
    range: 300,
    attackSpeed: 480,
    ammoRequired: 'arrow',
  },
  arrow: {
    id: 'arrow',
    name: 'Flecha de Sílex',
    category: 'ammo',
    description: 'Flechas afiladas con punta de piedra.',
    iconPixel: '↗️',
    color: '#d8b080',
    maxStack: 60,
  },
  retro_shotgun: {
    id: 'retro_shotgun',
    name: 'Escopeta 8-Bit',
    category: 'weapon',
    description: '¡Boom! Disparo devastador en cono que aniquila grupos de sombras.',
    iconPixel: '💥',
    color: '#e04000',
    maxStack: 1,
    damage: 130,
    range: 180,
    attackSpeed: 700,
    ammoRequired: 'shotgun_shell',
  },
  shotgun_shell: {
    id: 'shotgun_shell',
    name: 'Cartucho de Escopeta',
    category: 'ammo',
    description: 'Munición explosiva encontrada en cabañas abandonadas o fabricada.',
    iconPixel: '🟥',
    color: '#d82800',
    maxStack: 40,
  },
  torch: {
    id: 'torch',
    name: 'Antorcha Portátil',
    category: 'survival',
    description: 'Ilumina tus pasos en la oscuridad y te mantiene caliente.',
    iconPixel: '🔥',
    color: '#fc7400',
    maxStack: 10,
    lightRadius: 130,
    warmthRestore: 10,
    damage: 15,
  },
  bandage: {
    id: 'bandage',
    name: 'Vendaje Estéril',
    category: 'healing',
    description: 'Detiene hemorragias y cura 30 puntos de vida.',
    iconPixel: '🩹',
    color: '#f8f8f8',
    maxStack: 20,
    healHp: 30,
  },
  medkit: {
    id: 'medkit',
    name: 'Botiquín de Emergencia',
    category: 'healing',
    description: 'Tratamiento completo. Restaura 85 HP y elimina frío.',
    iconPixel: '🧰',
    color: '#d82800',
    maxStack: 5,
    healHp: 85,
    warmthRestore: 40,
  },
  wooden_wall: {
    id: 'wooden_wall',
    name: 'Barricada de Troncos',
    category: 'defense',
    description: 'Colócala para bloquear el paso de los monstruos hacia la fogata.',
    iconPixel: '🪵',
    color: '#885818',
    maxStack: 20,
    defenseHp: 180,
  },
  spike_trap: {
    id: 'spike_trap',
    name: 'Trampa de Estacas',
    category: 'defense',
    description: 'Empala a los enemigos que caminen sobre ella causándoles 70 de daño.',
    iconPixel: '📐',
    color: '#503000',
    maxStack: 15,
  },
  bear_trap: {
    id: 'bear_trap',
    name: 'Trampa de Oso de Acero',
    category: 'defense',
    description: 'Inmoviliza y causa 150 de daño masivo a monstruos y jefes.',
    iconPixel: '⛓️',
    color: '#585858',
    maxStack: 10,
  },
  fuel_pellet: {
    id: 'fuel_pellet',
    name: 'Pastilla de Combustible',
    category: 'resource',
    description: 'Combustible concentrado que aviva la fogata intensamente (+50 fuel).',
    iconPixel: '🔥',
    color: '#f8b800',
    maxStack: 30,
    fuelValue: 50,
  },
  forest_gold_coin: {
    id: 'forest_gold_coin',
    name: 'Moneda de Oro Antigua',
    category: 'special',
    description: 'Monedas perdidas de campistas de antaño. Úsalas en la tienda.',
    iconPixel: '🪙',
    color: '#fce000',
    maxStack: 9999,
  },
  ancient_relic: {
    id: 'ancient_relic',
    name: 'Reliquia del Bosque',
    category: 'special',
    description: 'Artefacto mágico que debilita al Wendigo y otorga inmenso poder.',
    iconPixel: '🔮',
    color: '#9858f8',
    maxStack: 10,
  },
  moon_flower: {
    id: 'moon_flower',
    name: 'Flor de la Luna Azul',
    category: 'quest',
    description: 'Planta luminiscente que solo florece cerca de las aguas prohibidas. Esencia de alquimia.',
    iconPixel: '🌸',
    color: '#3cbcfc',
    maxStack: 20,
    healHp: 20,
  },
  corrupted_essence: {
    id: 'corrupted_essence',
    name: 'Esencia Corrupta',
    category: 'quest',
    description: 'Fragmento de materia oscura obtenido al derrotar bestias nocturnas.',
    iconPixel: '🟣',
    color: '#6820a0',
    maxStack: 50,
  },
  ancient_tome: {
    id: 'ancient_tome',
    name: 'Grimorio de la Primera Llama',
    category: 'special',
    description: 'Libro milenario encuadernado en corteza de roble con secretos de la fundación del bosque.',
    iconPixel: '📖',
    color: '#f8b800',
    maxStack: 1,
  },
  cleansing_amulet: {
    id: 'cleansing_amulet',
    name: 'Amuleto Purificador',
    category: 'special',
    description: 'Joya bendecida que repele la niebla venenosa y protege contra la locura nocturna.',
    iconPixel: '🧿',
    color: '#58d854',
    maxStack: 1,
  },
  whispering_key: {
    id: 'whispering_key',
    name: 'Llave de los Susurros',
    category: 'quest',
    description: 'Llave forjada en metal estelar capaz de abrir el cofre prohibido del santuario.',
    iconPixel: '🗝️',
    color: '#fce000',
    maxStack: 5,
  },
};

// ============================================================================
// NARRATIVE ENGINE: BRANCHING DIALOGUE NODES WITH PLAYER CHOICES
// ============================================================================

import { DialogueNode, StoryEnding, LoreEntry } from '../types';

export const STORY_DIALOGUE_NODES: Record<string, DialogueNode> = {
  // --- VALERIA LA GUARDABOSQUES (CAMPAMENTO CENTRAL) ---
  valeria_intro: {
    id: 'valeria_intro',
    speaker: 'Valeria la Guardabosques',
    title: 'Superviviente del Puesto Forestal',
    icon: '🏹',
    text: '¡POR FIN DESPIERTAS! LLEVAS HORAS INCONSCIENTE TRAS EL CHOQUE. ESTE ES EL VALLE DE SAN TELMO... O LO QUE QUEDA DE ÉL TRAS LA GRAN NIEBLA. CADA NOCHE LAS SOMBRAS INTENTAN APAGAR NUESTRA LLAMA.',
    choices: [
      {
        id: 'valeria_ask_story',
        text: '1. ¿Qué ocurrió con este bosque y la niebla?',
        nextNodeId: 'valeria_story_history',
        faction: 'alquimia',
        alignmentValue: 2,
      },
      {
        id: 'valeria_ask_advice',
        text: '2. ¿Cómo mantengo vivo el campamento y la fogata?',
        nextNodeId: 'valeria_advice_fire',
        faction: 'fuego',
        alignmentValue: 3,
      },
      {
        id: 'valeria_ask_explore',
        text: '3. ¿Hay más personas vivas en este valle?',
        nextNodeId: 'valeria_survivors_hint',
        faction: 'vacio',
        alignmentValue: 1,
      },
      {
        id: 'valeria_leave',
        text: '4. Gracias Valeria, iré a recolectar madera.',
        nextNodeId: undefined,
      },
    ],
  },
  valeria_story_history: {
    id: 'valeria_story_history',
    speaker: 'Valeria la Guardabosques',
    title: 'Superviviente del Puesto Forestal',
    icon: '📜',
    text: 'EN 1986, UN ECLIPSE DESGARRÓ EL CIELO Y LIBERÓ UNA NIEBLA QUE DETUVO EL TIEMPO. SOLO EL FUEGO SAGRADO DE ESTE ALTAR IMPIDE QUE NOS CONVIRTIAMOS EN ESPECTROS. SI ALCANZAMOS EL DÍA 99, EL CICLO SE ROMPERÁ.',
    choices: [
      {
        id: 'valeria_ask_advice',
        text: '1. ¿Qué necesito hacer primero?',
        nextNodeId: 'valeria_advice_fire',
      },
      {
        id: 'valeria_leave',
        text: '2. Haré que este fuego nunca se apague.',
        nextNodeId: undefined,
        faction: 'fuego',
        alignmentValue: 4,
      },
    ],
  },
  valeria_advice_fire: {
    id: 'valeria_advice_fire',
    speaker: 'Valeria la Guardabosques',
    title: 'Superviviente del Puesto Forestal',
    icon: '🔥',
    text: 'USA EL BOTÓN (A) O ESPACIO PARA TALAR ÁRBOLES Y MINAR ROCAS. ACÉRCATE A LA FOGATA CON MADERA Y PULSA (B) O LA TECLA F PARA ALIMENTARLA. SI EL FUEGO SE APAGA, EL FRÍO Y LAS BESTIAS ACABARÁN CON TODO.',
    choices: [
      {
        id: 'valeria_reward_starter',
        text: '1. [Aceptar bendición de guardabosques (+50 Madera y 2 Vendajes)].',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 3,
      },
    ],
  },
  valeria_survivors_hint: {
    id: 'valeria_survivors_hint',
    speaker: 'Valeria la Guardabosques',
    title: 'Superviviente del Puesto Forestal',
    icon: '🏕️',
    text: 'HAY JAULAS CON SUPERVIVIENTES AL NORTE Y SUR. SI LOS LIBERAS ATACANDO LAS JAULAS, SE UNIRÁN AL CAMPAMENTO Y NOS AYUDARÁN A COLECTAR RECURSOS, CURAR HERIDAS Y DEFENDERNOS.',
    choices: [
      {
        id: 'valeria_leave',
        text: '1. Iré a rescatarlos de inmediato.',
        nextNodeId: undefined,
        action: 'accept_quest',
      },
    ],
  },

  // --- DRA. ELENA LA BOTÁNICA ---
  elena_intro: {
    id: 'elena_intro',
    speaker: 'Dra. Elena',
    title: 'Botánica del Santuario',
    icon: '🧪',
    text: 'ESTUDIO LAS PROPIEDADES DE LA FLORA DE ESTE VALLE. LAS BAYAS ROJAS APORTAN NUTRICIÓN, Y LAS MISTERIOSAS FLORES DE LUNA AZUL SOLO CRECEN CERCA DEL AGUA DURANTE EL ECLIPSE.',
    choices: [
      {
        id: 'elena_heal',
        text: '1. ¿Puedes curar mis heridas con tus ungüentos? (+40 Salud).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'alquimia',
        alignmentValue: 3,
      },
      {
        id: 'elena_quest',
        text: '2. ¿Qué usos tienen las Flores de Luna?',
        nextNodeId: 'elena_moon_flower_lore',
      },
      {
        id: 'elena_exit',
        text: '3. Volveré cuando encuentre ingredientes raros.',
        nextNodeId: undefined,
      },
    ],
  },
  elena_moon_flower_lore: {
    id: 'elena_moon_flower_lore',
    speaker: 'Dra. Elena',
    title: 'Botánica del Santuario',
    icon: '🌸',
    text: 'CON 3 FLORES DE LUNA Y RESINA PODEMOS SINTETIZAR POCIONES QUE RESTAURAN EL CALOR CORPORAL INCLUSO EN LAS NOCHES MÁS HELADAS. BÚSCALAS CERCA DE LOS MANANTIALES.',
    choices: [{ id: 'elena_exit', text: '1. Buscaré esas flores.', nextNodeId: undefined }],
  },

  // --- SARGENTO MATEO (DEFENSA Y TÁCTICAS) ---
  mateo_intro: {
    id: 'mateo_intro',
    speaker: 'Sargento Mateo',
    title: 'Defensor del Campamento',
    icon: '🛡️',
    text: '¡FIRMES! LAS SOMBRAS ATACAN EN OLEADAS A PARTIR DE LAS 20:00 HORAS. SI TE RODEAN, HAZ UNA RODADA DE ESQUIVE CON (B) O MAYÚS Y MANTÉN LA ESPADA EN ALTO.',
    choices: [
      {
        id: 'mateo_train',
        text: '1. Enséñame técnicas de combate defensivo (+15% Armadura).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 4,
      },
      {
        id: 'mateo_bosses',
        text: '2. ¿A qué amenazas nos enfrentamos en noches avanzadas?',
        nextNodeId: 'mateo_threats_lore',
      },
      {
        id: 'mateo_exit',
        text: '3. Estaré alerta, Sargento.',
        nextNodeId: undefined,
      },
    ],
  },
  mateo_threats_lore: {
    id: 'mateo_threats_lore',
    speaker: 'Sargento Mateo',
    title: 'Defensor del Campamento',
    icon: '💀',
    text: 'EN LA NOCHE 10 EL CIERVO CORROMPIDO ABRIRÁ LA PUERTA NORTE. EN LA NOCHE 50 VENDRÁ EL CULTISTA SUPREMO. Y EN LA NOCHE 99... EL WENDIGO ANCESTRAL EN PERSONA. ¡PREPARA TUS MEJORES FLECHAS Y TRAMPAS!',
    choices: [{ id: 'mateo_exit', text: '1. No le temo a la oscuridad.', nextNodeId: undefined }],
  },

  // --- CHEF RAMÓN (NUTRICIÓN Y SUPERVIVENCIA) ---
  ramon_intro: {
    id: 'ramon_intro',
    speaker: 'Chef Ramón',
    title: 'Cocinero del Campamento',
    icon: '🍲',
    text: '¡NADA COMO UN BUEN ESTOFADO CALIENTE PARA COMBATIR EL FRÍO DEL VALLE! SI ME TRAES CARNE DE CAZA Y SETAS, PREPARARÉ UN BANQUETE QUE MULTIPLICA TU RESISTENCIA.',
    choices: [
      {
        id: 'ramon_feed',
        text: '1. Tomar una sopa caliente de emergencia (+50 Hambre y Calor).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 2,
      },
      {
        id: 'ramon_exit',
        text: '2. Gracias Chef, iré a cazar presas.',
        nextNodeId: undefined,
      },
    ],
  },

  // --- EL ERUDITO VAELEN (RUINAS DE LA BIBLIOTECA / CUEVA) ---
  vaelen_intro: {
    id: 'vaelen_intro',
    speaker: 'Erudito Vaelen',
    title: 'El Cronista de las 99 Eras',
    icon: '🧙‍♂️',
    text: 'SALUDOS, CAMINANTE. ESTE BOSQUE NO ES UN LUGAR, SINO UN RELOJ TEMPORAL QUE CONSUME ALMAS CADA 99 NOCHES. ¿BUSCAS MERAMENTE SOBREVIVIR O CONOCER LA VERDAD TRAS EL ECLIPSE?',
    choices: [
      {
        id: 'vaelen_ask_lore',
        text: '1. ¿Qué es el "Reloj de las 99 Noches"?',
        nextNodeId: 'vaelen_lore_clock',
        faction: 'alquimia',
        alignmentValue: 2,
      },
      {
        id: 'vaelen_ask_survive',
        text: '2. Solo quiero mantener viva mi fogata y sobrevivir.',
        nextNodeId: 'vaelen_survive_path',
        faction: 'fuego',
        alignmentValue: 3,
      },
      {
        id: 'vaelen_ask_wendigo',
        text: '3. He oído hablar del Wendigo Primigenio. ¿Cómo lo destruyo?',
        nextNodeId: 'vaelen_wendigo_quest',
        faction: 'sombras',
        alignmentValue: 1,
      },
    ],
  },
  vaelen_lore_clock: {
    id: 'vaelen_lore_clock',
    speaker: 'Erudito Vaelen',
    title: 'El Cronista de las 99 Eras',
    icon: '📜',
    text: 'CADA NOCHE QUE EL FUEGO ARDE, EL VELO ENTRE REALIDADES SE DESGARRA. TRAEME UNA FLOR DE LUNA Y ESENCIA CORRUPTA; TE SINTETIZARÉ EL "AMULETO PURIFICADOR".',
    choices: [
      {
        id: 'vaelen_accept_quest',
        text: '1. Acepto la misión del alquimista.',
        nextNodeId: 'vaelen_quest_active',
        action: 'accept_quest',
        faction: 'alquimia',
        alignmentValue: 5,
      },
      {
        id: 'vaelen_deliver_items',
        text: '2. Tengo los ingredientes necesarios [Entregar Flor y Esencia].',
        nextNodeId: 'vaelen_crafted_amulet',
        action: 'give_item',
        requiredItem: 'moon_flower',
        rewardItem: 'cleansing_amulet',
        rewardCount: 1,
      },
      {
        id: 'vaelen_exit',
        text: '3. Debo volver antes de que caiga la noche.',
        nextNodeId: undefined,
      },
    ],
  },
  vaelen_survive_path: {
    id: 'vaelen_survive_path',
    speaker: 'Erudito Vaelen',
    title: 'El Cronista de las 99 Eras',
    icon: '🔥',
    text: 'NOBLE INTENTO. EL FUEGO ALCANZA SU MÁXIMO PODER EN EL FARO SAGRADO (NIVEL 5). RECOLECTA 2 RELIQUIAS Y MINERALES PARA CONSAGRAR LA LLAMA.',
    choices: [
      {
        id: 'vaelen_blessing',
        text: '1. Bendice mis armas con polvo ignífugo (+10% daño a bestias).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 4,
      },
      {
        id: 'vaelen_exit',
        text: '2. Gracias, volveré al campamento.',
        nextNodeId: undefined,
      },
    ],
  },
  vaelen_wendigo_quest: {
    id: 'vaelen_wendigo_quest',
    speaker: 'Erudito Vaelen',
    title: 'El Cronista de las 99 Eras',
    icon: '💀',
    text: 'EL WENDIGO NO ES UN MONSTRUO... ERA EL PRIMER SUPERVIVIENTE DE ESTE BOSQUE HACE UN MILENIO. SI CONSUMES SU CORAZÓN EN LA NOCHE 99, HEREDARÁS SU PODER O LO LIBERARÁS.',
    choices: [
      {
        id: 'vaelen_path_abyss',
        text: '1. Tomaré el trono de las sombras.',
        nextNodeId: undefined,
        faction: 'sombras',
        alignmentValue: 6,
      },
      {
        id: 'vaelen_path_liberate',
        text: '2. Liberaré su alma con el fuego purificador.',
        nextNodeId: undefined,
        faction: 'fuego',
        alignmentValue: 6,
      },
    ],
  },
  vaelen_crafted_amulet: {
    id: 'vaelen_crafted_amulet',
    speaker: 'Erudito Vaelen',
    title: 'El Cronista de las 99 Eras',
    icon: '✨',
    text: '¡MAGNÍFICO! HE FORJADO EL AMULETO PURIFICADOR. AHORA PUEDES EXAMINAR EL SANTUARIO CELESTIAL SIN SER DEVORADO POR LA LOCURA.',
    choices: [
      {
        id: 'vaelen_finish',
        text: '1. Guardar el amuleto sagrado.',
        nextNodeId: undefined,
      },
    ],
  },

  // --- MORRIGAN: LA ESPÍA DE LA LUNA SANGRIENTA ---
  morrigan_intro: {
    id: 'morrigan_intro',
    speaker: 'Morrigan',
    title: 'Emisaria de la Luna Carmesí',
    icon: '🩸',
    text: '¿SABES POR QUÉ LA LUNA SE TIÑE DE SANGRE CADA POCOS DÍAS? EL BOSQUE TIENE HAMBRE. OFRÉCELE TUS LINGOTES Y TE DARÉ EL PODER DE LA OSCURIDAD.',
    choices: [
      {
        id: 'morrigan_trade_blood',
        text: '1. Ofrecer 5 lingotes de hierro a cambio de 100 de Oro y 3 Esencias.',
        nextNodeId: 'morrigan_deal_done',
        action: 'trade',
        faction: 'sombras',
        alignmentValue: 4,
        requiredItem: 'iron_ingot',
        rewardItem: 'corrupted_essence',
        rewardCount: 3,
      },
      {
        id: 'morrigan_ask_ritual',
        text: '2. ¿Cuál es el secreto de la Luna Roja?',
        nextNodeId: 'morrigan_lore_blood',
        faction: 'vacio',
        alignmentValue: 3,
      },
      {
        id: 'morrigan_reject',
        text: '3. No pacto con las sombras.',
        nextNodeId: 'morrigan_rejected',
        faction: 'fuego',
        alignmentValue: 2,
      },
    ],
  },
  morrigan_deal_done: {
    id: 'morrigan_deal_done',
    speaker: 'Morrigan',
    title: 'Emisaria de la Luna Carmesí',
    icon: '🩸',
    text: 'UN TRATO EXQUISITO... LAS BESTIAS DE ESTA NOCHE SENTIRÁN EL TERROR DE TU HOJA.',
    choices: [{ id: 'morrigan_exit', text: '1. Retirarse.', nextNodeId: undefined }],
  },
  morrigan_lore_blood: {
    id: 'morrigan_lore_blood',
    speaker: 'Morrigan',
    title: 'Emisaria de la Luna Carmesí',
    icon: '🌑',
    text: 'EN LA NOCHE 50 Y 99, EL ECLIPSE TOTAL ABRIRÁ LA PUERTA ESTELAR. QUIEN POSEA 3 RELIQUIAS Y EL GRIMORIO PODRÁ DISOLVER EL BOSQUE EN EL VACÍO.',
    choices: [{ id: 'morrigan_exit', text: '1. Tomar nota del presagio.', nextNodeId: undefined }],
  },
  morrigan_rejected: {
    id: 'morrigan_rejected',
    speaker: 'Morrigan',
    title: 'Emisaria de la Luna Carmesí',
    icon: '👁️',
    text: 'TONTO MORTAL... EL FUEGO SIEMPRE SE APAGA. CUANDO LLEGUE EL FRÍO ETERNO, CLAMARÁS POR LA LUNA.',
    choices: [{ id: 'morrigan_exit', text: '1. Marcharse.', nextNodeId: undefined }],
  },

  // --- EL FANTASMA DE ALDEN (PRIMER SUPERVIVIENTE) ---
  alden_intro: {
    id: 'alden_intro',
    speaker: 'Fantasma de Alden',
    title: 'Primer Explorador Caído',
    icon: '👻',
    text: 'HACE CIEN AÑOS FUI COMO TÚ... TÉMPORE, CONGELADO Y HAMBRIENTO. MI TUMBA YACE AL ESTE. ENCUENTRA MI LLAVE Y ABRE MI VIEJO COFRE.',
    choices: [
      {
        id: 'alden_quest',
        text: '1. Descansaré tu espíritu, Alden. ¿Dónde está tu llave?',
        nextNodeId: 'alden_key_location',
        faction: 'fuego',
        alignmentValue: 3,
      },
      {
        id: 'alden_warn',
        text: '2. ¿Cómo caíste en la noche?',
        nextNodeId: 'alden_death_warning',
      },
      {
        id: 'alden_leave',
        text: '3. [Desvanecerse en la niebla]',
        nextNodeId: undefined,
      },
    ],
  },
  alden_key_location: {
    id: 'alden_key_location',
    speaker: 'Fantasma de Alden',
    title: 'Primer Explorador Caído',
    icon: '🗝️',
    text: 'LA LLAVE ESTÁ ESCONDIDA EN EL POZO DE LOS SUSURROS. DEPOSITA UNA MONEDA EN EL POZO Y TE LA ENTREGARÁ.',
    choices: [{ id: 'alden_exit', text: '1. Iré al Pozo.', nextNodeId: undefined, action: 'accept_quest' }],
  },
  alden_death_warning: {
    id: 'alden_death_warning',
    speaker: 'Fantasma de Alden',
    title: 'Primer Explorador Caído',
    icon: '⚠️',
    text: 'EL FRÍO NO TE MATA DIRECTAMENTE... PRIMERO APAGA TUS SENTIDOS, DESPUÉS HACE QUE LAS SOMBRAS PAREZCAN REFUGIO. NUNCA TE ALEJES DE LA LUZ.',
    choices: [{ id: 'alden_exit', text: '1. Guardaré el consejo en mi memoria.', nextNodeId: undefined }],
  },

  // --- MONOLITO DE LAS SOMBRAS ANCESTRALES (INTERACTIVE PROP) ---
  prop_monolith: {
    id: 'prop_monolith',
    speaker: 'Monolito Ancestral',
    title: 'Pilar Rúnico Prehistórico',
    icon: '🗿',
    text: 'UN MONOLITO DE BASALTO NEGRO CUBIERTO DE JEROGLÍFICOS RETRO QUE VIBRAN AL CONTACTO. UN TEXTO DICE: "AQUEL QUE PURIFIQUE EL BOSQUE REINARÁ EN EL ALBA".',
    choices: [
      {
        id: 'monolith_read',
        text: '1. Traducir las runas del monolito (+50 XP, Desbloquear Lore).',
        nextNodeId: undefined,
        action: 'unlock_lore',
        faction: 'alquimia',
        alignmentValue: 3,
      },
      {
        id: 'monolith_touch',
        text: '2. Canalizar energía rúnica (Restaura todo el calor y estamina).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 2,
      },
      {
        id: 'monolith_leave',
        text: '3. Dejar el monolito en paz.',
        nextNodeId: undefined,
      },
    ],
  },

  // --- POZO DE LOS SUSURROS (INTERACTIVE PROP) ---
  prop_well: {
    id: 'prop_well',
    speaker: 'Pozo de los Susurros',
    title: 'Manantial de Aguas Profundas',
    icon: '🕳️',
    text: 'EL AGUA DEL POZO REFLEJA UN CIELO CON DOS LUNAS. UN SUSURRO EMERGE DESDE LAS PROFUNDIDADES: "UNA OFRENDA POR UN SECRETO..."',
    choices: [
      {
        id: 'well_drop_coin',
        text: '1. Arrojar 10 Monedas de Oro [Obtener Llave de los Susurros].',
        nextNodeId: 'well_reward_key',
        action: 'trade',
        requiredItem: 'forest_gold_coin',
        rewardItem: 'whispering_key',
        rewardCount: 1,
        faction: 'vacio',
        alignmentValue: 3,
      },
      {
        id: 'well_drink',
        text: '2. Beber agua sagrada (+30 Salud, -20 Hambre).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'alquimia',
        alignmentValue: 2,
      },
      {
        id: 'well_leave',
        text: '3. Alejarse del borde.',
        nextNodeId: undefined,
      },
    ],
  },
  well_reward_key: {
    id: 'well_reward_key',
    speaker: 'Pozo de los Susurros',
    title: 'Manantial de Aguas Profundas',
    icon: '🗝️',
    text: 'UNA LLAVE ANTIGUA BRILLANTE FLOTA DESDE EL FONDO Y CAE EN TUS MANOS. EL POZO SUSURRA: "ABRE LA TUMBA DEL GUERRERO..."',
    choices: [{ id: 'well_exit', text: '1. Tomar la llave.', nextNodeId: undefined }],
  },

  // --- ALTAR CELESTIAL DE LA LUNA AZUL ---
  prop_altar: {
    id: 'prop_altar',
    speaker: 'Altar de la Luna Azul',
    title: 'Relicario de la Trascendencia',
    icon: '⛩️',
    text: 'EL ALTAR EXIGE UN SACRIFICIO O UNA OFRENDA DE LUZ. ¿CUÁL ES TU VERDADERO DESTINO EN ESTE BOSQUE?',
    choices: [
      {
        id: 'altar_offer_flower',
        text: '1. Consagrar una Flor de la Luna Azul (Desbloquear Senda Alquímica).',
        nextNodeId: undefined,
        action: 'trade',
        requiredItem: 'moon_flower',
        faction: 'alquimia',
        alignmentValue: 8,
      },
      {
        id: 'altar_offer_relic',
        text: '2. Insertar una Reliquia Antigua (Canalizar poder cósmico).',
        nextNodeId: undefined,
        action: 'trade',
        requiredItem: 'ancient_relic',
        faction: 'vacio',
        alignmentValue: 10,
      },
      {
        id: 'altar_pray',
        text: '3. Rezar por los caídos (Restaura salud al máximo).',
        nextNodeId: undefined,
        action: 'heal',
        faction: 'fuego',
        alignmentValue: 5,
      },
    ],
  },
};

// ============================================================================
// STORY ENDINGS CATALOG (BRANCHING MULTI-ENDINGS & EXPERIMENTAL EPILOGUES)
// ============================================================================

export const STORY_ENDINGS_CATALOG: StoryEnding[] = [
  {
    id: 'ending_flame_guardian',
    title: 'Final I: El Guardián Eterno de la Llama',
    subtitle: 'Senda de la Humanidad y el Fuego',
    description: 'Sobreviviste las 99 noches manteniendo el Faro Sagrado en su máximo esplendor, protegiendo a todos los campistas rescatados.',
    epilogue: 'El amanecer de la Noche 100 rasgó para siempre la densa niebla. Guiados por la luz inmaculada de tu faro, los campistas supervivientes fundaron una nueva civilización en los valles del este. Tu nombre fue tallado en piedra como el Guardián de la Primera Llama.',
    category: 'fuego',
    icon: '🔥',
    unlocked: false,
  },
  {
    id: 'ending_wendigo_ascension',
    title: 'Final II: El Señor del Bosque Oscuro',
    subtitle: 'Senda de las Sombras y el Pacto de Sangre',
    description: 'Derrotaste al Wendigo tras haber abrazado el poder corrupto de Morrigan y consumiste su esencia estelar.',
    epilogue: 'Al cesar el latido del Wendigo primigenio, el bosque no murió; coronó a su nuevo monarca. Tus ojos se encendieron con el fuego carmesí de la Luna Sangrienta. Los lobos y las criaturas de la noche ya no te atacan; ahora se postran a tus pies. Eres el nuevo mito que asustará a las futuras generaciones.',
    category: 'sombras',
    icon: '👑',
    unlocked: false,
  },
  {
    id: 'ending_alchemical_dawn',
    title: 'Final III: La Transmutación del Amanecer',
    subtitle: 'Senda de la Alquimia y la Ciencia Olvidada',
    description: 'Completaste los enigmas del Erudito Vaelen y purificaste las aguas del bosque con el Elixir de la Luna Azul.',
    epilogue: 'Al verter el elixir en las raíces del Gran Roble Central, una ola de energía dorada curó la corrupción del suelo. Los árboles negros florecieron con pétalos de zafiro y las bestias malditas recuperaron su forma original de ciervos y aves cantarinas. Has deshecho la maldición de mil años.',
    category: 'alquimia',
    icon: '🧪',
    unlocked: false,
  },
  {
    id: 'ending_cosmic_eclipse',
    title: 'Final IV: Trascendencia del Eclipse Cósmico',
    subtitle: 'Senda del Vacío y la Puerta Estelar',
    description: 'Reuniste las Reliquias Antiguas y activaste el Altar de las Dos Lunas durante la noche del eclipse total.',
    epilogue: 'El cielo se abrió en una espiral geométrica de 8-bits de pura energía dimensional. El bosque, la cabaña y el tiempo mismo se doblaron sobre sí mismos. Comprendiste que el bosque no era una trampa terrestre, sino un experimento de una inteligencia superior para probar la voluntad del espíritu humano. Diste un paso hacia las estrellas.',
    category: 'vacio',
    icon: '🌌',
    unlocked: false,
  },
  {
    id: 'ending_survivor_exodus',
    title: 'Final V: El Éxodo de los Condenados',
    subtitle: 'Senda del Liderazgo y Rescate Total',
    description: 'Rescataste a todos los campistas atrapados y escaparon juntos a través del paso montañoso del norte.',
    epilogue: 'Llevando antorchas y suministros forjados en tu yunque, tu caravana cruzó el puente de tablones mientras el Wendigo rugía impotente en la distancia. Ninguna vida se perdió en la expedición. La leyenda de tu valentía perdurará por siempre en los libros de historia.',
    category: 'supervivencia',
    icon: '🏕️',
    unlocked: false,
  },
  {
    id: 'ending_time_loop',
    title: 'Final Secreto VI: El Bucle del Ermitaño',
    subtitle: 'Paradoja Temporal Retro',
    description: 'Descubriste el grimorio antiguo en la cueva secreta y comprendiste la verdadera identidad del Sabio.',
    epilogue: 'Al abrir el grimorio sellado, encontraste tus propias notas escritas con tu propia letra hace un siglo. Miraste tu reflejo en el agua del pozo: tu barba era blanca y tu túnica roja. Ahora entiendes tu deber: sentarte en la cueva y esperar al próximo superviviente.',
    category: 'vacio',
    icon: '⏳',
    unlocked: false,
  },
];

// ============================================================================
// LORE CODEX ENTRIES
// ============================================================================

export const LORE_CODEX_ENTRIES: LoreEntry[] = [
  {
    id: 'lore_origin_fog',
    title: 'Capítulo I: El Origen de la Niebla',
    subtitle: 'Crónicas de la Primera Expedición (Año 1886)',
    category: 'antigua_civilizacion',
    content: 'La niebla no es vapor natural; es el aliento de una entidad interestelar que cayó en el cráter central durante el gran eclipse. Aquellos que inhalan sus partículas durante la noche comienzan a escuchar murmullos que incitan a abandonar el fuego.',
    unlocked: true,
  },
  {
    id: 'lore_wendigo_curse',
    title: 'Capítulo II: La Maldición del Cazador',
    subtitle: 'Memorias del Guardabosques',
    category: 'maldicion_wendigo',
    content: 'El primer hombre que sucumbió al hambre extrema en el invierno de 1890 comió la carne impregnada de la niebla. Su cuerpo mutó en astas de hueso y garras de hierro. Se convirtió en el Wendigo, incapaz de saciarse pero temeroso del fuego ardiente.',
    unlocked: false,
  },
  {
    id: 'lore_sacred_fire',
    title: 'Capítulo III: La Alquimia de la Llama',
    subtitle: 'Tratado del Erudito Vaelen',
    category: 'alquimia',
    content: 'La madera de los pinos sagrados contiene resina concentrada que al arder emite fotones en una frecuencia capaz de desintegrar la sustancia umbría de los monstruos. Entre más alta sea la fogata, más amplio será el santuario.',
    unlocked: false,
  },
  {
    id: 'lore_eclipse_portal',
    title: 'Capítulo IV: La Puerta de las Dos Lunas',
    subtitle: 'Fragmento de Grimorio Estelar',
    category: 'eclipse_cosmico',
    content: 'Cada 99 noches se alinea el eclipse dimensional. Quien combine tres reliquias antiguas en el Altar de las Sombras podrá decidir si cerrar el portal para siempre o cruzarlo hacia el infinito.',
    unlocked: false,
  },
];


export const CRAFTING_RECIPES: CraftingRecipe[] = [
  {
    id: 'recipe_torch',
    result: 'torch',
    resultCount: 2,
    ingredients: [
      { item: 'wood', count: 2 },
      { item: 'stone', count: 1 },
    ],
    category: 'survival',
    name: 'Antorcha (x2)',
    description: 'Crea 2 antorchas para iluminar tu camino en la noche.',
  },
  {
    id: 'recipe_wooden_axe',
    result: 'wooden_axe',
    resultCount: 1,
    ingredients: [
      { item: 'wood', count: 5 },
      { item: 'stone', count: 3 },
    ],
    category: 'tools',
    name: 'Hacha de Leñador',
    description: 'Herramienta básica para talar madera rápidamente.',
  },
  {
    id: 'recipe_wooden_club',
    result: 'wooden_club',
    resultCount: 1,
    ingredients: [{ item: 'wood', count: 4 }],
    category: 'weapons',
    name: 'Garrote de Madera',
    description: 'Arma pesada para golpear bestias nocturnas.',
  },
  {
    id: 'recipe_hunting_spear',
    result: 'hunting_spear',
    resultCount: 1,
    requiresCampfireLevel: 1,
    ingredients: [
      { item: 'wood', count: 6 },
      { item: 'stone', count: 4 },
    ],
    category: 'weapons',
    name: 'Lanza de Caza',
    description: 'Lanza de largo alcance para cazar ciervos y defenderse.',
  },
  {
    id: 'recipe_slingshot',
    result: 'slingshot',
    resultCount: 1,
    requiresCampfireLevel: 1,
    ingredients: [{ item: 'wood', count: 6 }],
    category: 'weapons',
    name: 'Tirachinas Rápido',
    description: 'Arma a distancia para disparar piedras.',
  },
  {
    id: 'recipe_stone_ammo',
    result: 'stone_ammo',
    resultCount: 10,
    ingredients: [{ item: 'stone', count: 2 }],
    category: 'weapons',
    name: 'Piedras de Proyectil (x10)',
    description: 'Munición económica para el tirachinas.',
  },
  {
    id: 'recipe_bandage',
    result: 'bandage',
    resultCount: 2,
    ingredients: [
      { item: 'berries', count: 4 },
      { item: 'wood', count: 2 },
    ],
    category: 'survival',
    name: 'Vendaje (x2)',
    description: 'Hierbas y fibras para curar 30 de vida.',
  },
  {
    id: 'recipe_cooked_meat',
    result: 'cooked_meat',
    resultCount: 1,
    requiresCampfireLevel: 1,
    ingredients: [
      { item: 'raw_meat', count: 1 },
      { item: 'wood', count: 1 },
    ],
    category: 'food',
    name: 'Cocinar Bife Asado',
    description: 'Asa carne en el fuego para restaurar +45 hambre y +30 HP.',
  },
  {
    id: 'recipe_mushroom_soup',
    result: 'mushroom_soup',
    resultCount: 1,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'mushroom', count: 3 },
      { item: 'berries', count: 2 },
      { item: 'wood', count: 2 },
    ],
    category: 'food',
    name: 'Sopa Caliente',
    description: 'Sopa reparadora que cura salud, hambre y frío.',
  },
  {
    id: 'recipe_wooden_wall',
    result: 'wooden_wall',
    resultCount: 2,
    requiresCampfireLevel: 1,
    ingredients: [{ item: 'wood', count: 6 }],
    category: 'defense',
    name: 'Barricadas (x2)',
    description: 'Muros para rodear tu campamento y bloquear monstruos.',
  },
  {
    id: 'recipe_spike_trap',
    result: 'spike_trap',
    resultCount: 2,
    requiresCampfireLevel: 1,
    ingredients: [
      { item: 'wood', count: 5 },
      { item: 'stone', count: 3 },
    ],
    category: 'defense',
    name: 'Trampas de Estacas (x2)',
    description: 'Daña a los monstruos que intenten cruzar.',
  },
  {
    id: 'recipe_iron_ingot',
    result: 'iron_ingot',
    resultCount: 1,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'iron_ore', count: 2 },
      { item: 'wood', count: 4 },
    ],
    category: 'tools',
    name: 'Fundir Lingote de Hierro',
    description: 'Funde mineral de hierro en la forja de la fogata.',
  },
  {
    id: 'recipe_iron_axe',
    result: 'iron_axe',
    resultCount: 1,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'iron_ingot', count: 3 },
      { item: 'wood', count: 5 },
    ],
    category: 'tools',
    name: 'Hacha de Hierro Reforzada',
    description: 'Hacha de alto rendimiento y letalidad.',
  },
  {
    id: 'recipe_hunting_bow',
    result: 'hunting_bow',
    resultCount: 1,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'wood', count: 8 },
      { item: 'stone', count: 4 },
    ],
    category: 'weapons',
    name: 'Arco de Caza Reforzado',
    description: 'Dispara flechas de gran alcance y daño.',
  },
  {
    id: 'recipe_arrows',
    result: 'arrow',
    resultCount: 8,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'wood', count: 3 },
      { item: 'stone', count: 2 },
    ],
    category: 'weapons',
    name: 'Flechas (x8)',
    description: 'Munición precisa para el arco.',
  },
  {
    id: 'recipe_machete',
    result: 'machete',
    resultCount: 1,
    requiresCampfireLevel: 3,
    ingredients: [
      { item: 'iron_ingot', count: 4 },
      { item: 'wood', count: 4 },
    ],
    category: 'weapons',
    name: 'Machete Legendario',
    description: 'Arma blanca formidable y ultra rápida.',
  },
  {
    id: 'recipe_bear_trap',
    result: 'bear_trap',
    resultCount: 1,
    requiresCampfireLevel: 3,
    ingredients: [
      { item: 'iron_ingot', count: 2 },
      { item: 'stone', count: 4 },
    ],
    category: 'defense',
    name: 'Trampa de Oso de Acero',
    description: 'Atrapa y causa 150 de daño devastador.',
  },
  {
    id: 'recipe_medkit',
    result: 'medkit',
    resultCount: 1,
    requiresCampfireLevel: 3,
    ingredients: [
      { item: 'bandage', count: 3 },
      { item: 'mushroom_soup', count: 1 },
    ],
    category: 'survival',
    name: 'Botiquín Completo',
    description: 'Cura +85 HP y restaura calor.',
  },
  {
    id: 'recipe_fuel_pellet',
    result: 'fuel_pellet',
    resultCount: 3,
    requiresCampfireLevel: 2,
    ingredients: [
      { item: 'wood', count: 6 },
      { item: 'mushroom', count: 2 },
    ],
    category: 'survival',
    name: 'Pastillas de Combustible (x3)',
    description: 'Combustible super concentrado que mantiene la llama.',
  },
  {
    id: 'recipe_shotgun_shell',
    result: 'shotgun_shell',
    resultCount: 4,
    requiresCampfireLevel: 4,
    ingredients: [
      { item: 'iron_ingot', count: 2 },
      { item: 'stone', count: 3 },
    ],
    category: 'weapons',
    name: 'Cartuchos Escopeta (x4)',
    description: 'Munición de alto calibre para la escopeta 8-bit.',
  },
  {
    id: 'recipe_retro_shotgun',
    result: 'retro_shotgun',
    resultCount: 1,
    requiresCampfireLevel: 4,
    ingredients: [
      { item: 'iron_ingot', count: 8 },
      { item: 'wood', count: 12 },
      { item: 'ancient_relic', count: 1 },
    ],
    category: 'weapons',
    name: 'Escopeta 8-Bit Devastadora',
    description: 'El arma suprema de supervivencia.',
  },
];

export const SKILL_NODES: SkillNode[] = [
  {
    id: 'lumberjack',
    name: 'Maestro Leñador',
    description: 'Tala árboles un 25% más rápido y obtén +1 madera extra por árbol.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '🪓',
    effect: '+25% velocidad tala, +1 madera',
  },
  {
    id: 'iron_stomach',
    name: 'Estómago de Hierro',
    description: 'El hambre decae 20% más lento y la comida sana un 25% más.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '🍖',
    effect: '-20% consumo hambre, +25% curación',
  },
  {
    id: 'pyromaniac',
    name: 'Guardián del Fuego',
    description: 'La fogata consume 25% menos combustible y otorga +20 de radio de luz.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '🔥',
    effect: '-25% gasto leña, +radio de luz',
  },
  {
    id: 'beast_hunter',
    name: 'Cazador Experto',
    description: 'Inflige +20% más de daño a todos los monstruos y animales.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '⚔️',
    effect: '+20% daño global',
  },
  {
    id: 'ninja_roll',
    name: 'Agilidad Sombría',
    description: 'Reduce el enfriamiento del esquive y aumenta la velocidad de movimiento.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '💨',
    effect: '-20% CD rodar, +15% velocidad',
  },
  {
    id: 'cold_blood',
    name: 'Piel Curtida',
    description: 'Pierdes calor un 30% más lento en la noche helada.',
    maxLevel: 5,
    costPerLevel: 1,
    icon: '❄️',
    effect: '+30% resistencia al frío',
  },
];

export const COSMETIC_SKINS = [
  {
    id: 'classic',
    name: 'Campista Clásico',
    description: 'El superviviente original con chaqueta roja y gorro de lana.',
    priceGold: 0,
    colorHead: '#e4a444',
    colorBody: '#d82800',
    colorPants: '#2038ec',
    rarity: 'Común',
  },
  {
    id: 'lumberjack_master',
    name: 'Leñador Barbudo',
    description: 'Veterano de los bosques con camisa a cuadros.',
    priceGold: 300,
    colorHead: '#a87830',
    colorBody: '#881400',
    colorPants: '#503000',
    rarity: 'Raro',
  },
  {
    id: 'shadow_hunter',
    name: 'Cazador de Sombras',
    description: 'Acecha a las bestias vestido con ropajes oscuros y capa.',
    priceGold: 600,
    colorHead: '#585858',
    colorBody: '#202020',
    colorPants: '#440068',
    rarity: 'Épico',
  },
  {
    id: 'retro_hero',
    name: 'Héroe 8-Bit NES',
    description: 'Inspirado en los guerreros clásicos de las consolas de 1985.',
    priceGold: 800,
    colorHead: '#f8d878',
    colorBody: '#3cbcfc',
    colorPants: '#fce000',
    rarity: 'Épico',
  },
  {
    id: 'hazmat',
    name: 'Científico Hazmat',
    description: 'Traje protector amarillo contra niebla y radiación.',
    priceGold: 1000,
    colorHead: '#fce000',
    colorBody: '#e4a444',
    colorPants: '#202020',
    rarity: 'Legendario',
  },
  {
    id: 'shaman_forest',
    name: 'Chamán Ancestral',
    description: 'Portador de los secretos de los espíritus del bosque y calavera.',
    priceGold: 1500,
    colorHead: '#f8f8f8',
    colorBody: '#9858f8',
    colorPants: '#004400',
    rarity: 'Mítico',
  },
];

export const COSMETIC_PETS = [
  {
    id: 'none',
    name: 'Sin Mascota',
    description: 'Viaja en solitario por el bosque.',
    priceGold: 0,
    icon: '❌',
  },
  {
    id: 'wolf_pup',
    name: 'Lobezno Valiente',
    description: 'Aúlla cuando los monstruos se acercan y muerde a enemigos cercanos.',
    priceGold: 400,
    icon: '🐺',
  },
  {
    id: 'night_owl',
    name: 'Búho Centinela',
    description: 'Amplía tu campo de visión nocturno y detecta cofres ocultos.',
    priceGold: 650,
    icon: '🦉',
  },
  {
    id: 'forest_fox',
    name: 'Zorro Astuto',
    description: 'Recolecta bayas y madera cercana automáticamente para ti.',
    priceGold: 850,
    icon: '🦊',
  },
  {
    id: 'mini_golem',
    name: 'Mini Golem de Piedra',
    description: 'Absorbe parte del daño que recibes y aturde enemigos.',
    priceGold: 1200,
    icon: '🗿',
  },
];

export const FIRE_STYLES = [
  {
    id: 'classic_orange',
    name: 'Fuego Cálido Tradicional',
    description: 'Llamas anaranjadas clásicas de leña crepitante.',
    priceGold: 0,
    colorFlame: '#fc7400',
    colorGlow: 'rgba(252, 116, 0, 0.4)',
  },
  {
    id: 'mystic_blue',
    name: 'Llama Azul Espectral',
    description: 'Fuego místico de color zafiro que ahuyenta fantasmas.',
    priceGold: 350,
    colorFlame: '#3cbcfc',
    colorGlow: 'rgba(60, 188, 252, 0.4)',
  },
  {
    id: 'infernal_green',
    name: 'Fuego Tóxico Esmeralda',
    description: 'Llama sobrenatural verde fosforescente.',
    priceGold: 500,
    colorFlame: '#58d854',
    colorGlow: 'rgba(88, 216, 84, 0.4)',
  },
  {
    id: 'sacred_gold',
    name: 'Fuego Solar Sagrado',
    description: 'Fuego dorado ardiente que ilumina el doble de radio.',
    priceGold: 900,
    colorFlame: '#fce000',
    colorGlow: 'rgba(252, 224, 0, 0.5)',
  },
];

export interface CampfireUpgradeDef {
  level: number;
  name: string;
  fuelCapacity: number;
  lightRadius: number;
  warmthRange: number;
  cost: { item: ItemType; count: number }[];
  unlockedCrafts: string;
}

export const CAMPFIRE_UPGRADES: CampfireUpgradeDef[] = [
  {
    level: 1,
    name: 'Fogata de Ramas',
    fuelCapacity: 100,
    lightRadius: 160,
    warmthRange: 140,
    cost: [],
    unlockedCrafts: 'Nivel 1 de Crafteo',
  },
  {
    level: 2,
    name: 'Anillo de Piedras Reforzado',
    fuelCapacity: 200,
    lightRadius: 230,
    warmthRange: 200,
    cost: [
      { item: 'wood', count: 15 },
      { item: 'stone', count: 12 },
    ],
    unlockedCrafts: 'Fundición de Hierro, Sopa y Flechas',
  },
  {
    level: 3,
    name: 'Hoguera de Campamento Mayor',
    fuelCapacity: 350,
    lightRadius: 300,
    warmthRange: 260,
    cost: [
      { item: 'wood', count: 25 },
      { item: 'stone', count: 20 },
      { item: 'iron_ingot', count: 5 },
    ],
    unlockedCrafts: 'Machete, Botiquines y Trampas de Oso',
  },
  {
    level: 4,
    name: 'Forja Térmica Fortificada',
    fuelCapacity: 500,
    lightRadius: 380,
    warmthRange: 330,
    cost: [
      { item: 'wood', count: 40 },
      { item: 'stone', count: 30 },
      { item: 'iron_ingot', count: 12 },
    ],
    unlockedCrafts: 'Escopeta 8-Bit y Cartuchos',
  },
  {
    level: 5,
    name: 'Faro Sagrado Eterno',
    fuelCapacity: 800,
    lightRadius: 480,
    warmthRange: 420,
    cost: [
      { item: 'wood', count: 60 },
      { item: 'stone', count: 50 },
      { item: 'iron_ingot', count: 20 },
      { item: 'ancient_relic', count: 2 },
    ],
    unlockedCrafts: 'Protección Absoluta y Regeneración Sagrada',
  },
];
